
class labels(object):

    # 금융 > 은행
    KRX은행               = '5046'
    KODEX은행             = '091170'
    TIGER은행             = '091220'
    KB금융                = '105560'
    하나금융지주          = '086790'
    DGB금융지주           = '139130'
    신한지주              = '055550'
    기업은행              = '024110'
    BNK금융지주           = '138930'
    우리금융지주          = '316140'
    상상인                = '038540'
    은행 = [
        KB금융,
        하나금융지주,
        DGB금융지주,
        신한지주,
        기업은행,
        BNK금융지주,
        우리금융지주,
        상상인
    ]

    # 미디어엔터테인먼트 > 플랫폼
    아프리카TV      = '067160'


class crypto(object):

    # CRYPTO
    BTC     = 'BTC'
    ETH     = 'ETH'
    BNB     = 'BNB'
    USDT    = 'USDT'
    SOL     = 'SOL'
    ADA     = 'ADA'
    XRP     = 'XRP'
    DOT     = 'DOT'
    USDC    = 'USDC'
    DOGE    = 'DOGE'
    SHIB    = 'SHIB'
    AVAX    = 'AVAX'
    LTC     = 'LTC'
    WBTC    = 'WBTC'
    BUSD    = 'BUSD'
    CRO     = 'CRO'
    UNI     = 'UNI'
    LINK    = 'LINK'
    ALGO    = 'ALGO'
    BCH     = 'BCH'
    MATIC   = 'MATIC'
    VET     = 'VET'
    XLM     = 'XLM'
    AXS     = 'AXS'
    MANA    = 'MANA'
    ICP     = 'ICP'
    TRX     = 'TRX'
    FTT     = 'FTT'
    UST     = 'UST'
    FIL     = 'FIL'
    DAI     = 'DAI'
    ETC     = 'ETC'
    EGLD    = 'EGLD'
    ATOM    = 'ATOM'
    THETA   = 'THETA'
    BTCB    = 'BTCB'
    HBAR    = 'HBAR'
    NEAR    = 'NEAR'
    FTM     = 'FTM'
    XTZ     = 'XTZ'
    GRT     = 'GRT'
    XMR     = 'XMR'
    HNT     = 'HNT'
    EOS     = 'EOS'
    SAND    = 'SAND'
    KLAY    = 'KLAY'
    FLOW    = 'FLOW'
    CAKE    = 'CAKE'
    AAVE    = 'AAVE'
    MIOTA   = 'MIOTA'
    XEC     = 'XEC'
    KDA     = 'KDA'
    LRC     = 'LRC'
    LEO     = 'LEO'
    KSM     = 'KSM'
    NEO     = 'NEO'
    BSV     = 'BSV'
    MKR     = 'MKR'
    QNT     = 'QNT'
    ENJ     = 'ENJ'
    CHZ     = 'CHZ'
    RUNE    = 'RUNE'
    ONE     = 'ONE'
    STX     = 'STX'
    WAVES   = 'WAVES'
    BTT     = 'BTT'
    HOT     = 'HOT'
    AMP     = 'AMP'
    ZEC     = 'ZEC'
    AR      = 'AR'
    DASH    = 'DASH'
    COMP    = 'COMP'
    KCS     = 'KCS'
    CELO    = 'CELO'
    CRV     = 'CRV'
    NEXO    = 'NEXO'
    IOTX    = 'IOTX'
    TFUEL   = 'TFUEL'
    WAXP    = 'WAXP'
    HT      = 'HT'
    XEM     = 'XEM'
    BAT     = 'BAT'
    OKB     = 'OKB'
    DCR     = 'DCR'
    ICX     = 'ICX'
    QTUM    = 'QTUM'
    OMG     = 'OMG'
    TUSD    = 'TUSD'
    MINA    = 'MINA'
    YFI     = 'YFI'
    RVN     = 'RVN'
    VGX     = 'VGX'
    SUSHI   = 'SUSHI'
    UMA     = 'UMA'
    AUDIO   = 'AUDIO'
    REV     = 'REV'
    SCRT    = 'SCRT'
    ZIL     = 'ZIL'
    VLX     = 'VLX'

    _tickers = vars()
    @property
    def tickers(self) -> list:
        return [v for v in self._tickers.values() if isinstance(v, str)][2:]
