# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: KRX Market Map

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
          python-version: '3.8'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run application
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        python "./update.py"
    - name: Commits
      run: |
        git config --local user.email "jhlee_0319@naver.com"
        git config --local user.name "ACTIONS"
        git add -A
        git commit -m "AFTER MARKET UPDATE ON ACTIONS @ ${{ steps.ydate.outputs.ydate }}"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $ 
